name: blaster_manager
description: "Gerenciamento profissional de shows pirotécnicos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ícones padrão
  cupertino_icons: ^1.0.2

  # Banco de Dados
  sqflite: ^2.3.2
  path: ^1.9.0

  # Gerenciamento de Estado
  provider: ^6.1.1

  # Formatação
  intl: ^0.19.0

  # PDF e Impressão
  pdf: ^3.10.0
  printing: ^5.11.0

  # Agenda
  add_2_calendar: ^3.0.1

  # --- NOVOS PACOTES (VERSÕES ATUALIZADAS) ---
  # Atualizado para v9 (corrige erros de compilação Android)
  share_plus: ^9.0.0
  
  # Atualizado para v8 (corrige o erro 'Registrar' que você teve)
  file_picker: ^8.0.0 
  
  # Gráficos
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

# Configuração da Logo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/icon.png"